/*
 *
 * Automatically generated file; DO NOT EDIT.
 * Unikraft/0.3.1~6636dfc-custom Configuration
 *
 */
#define CONFIG_KVM_KERNEL_SERIAL_CONSOLE 1
#define CONFIG_DEBUG_SYMBOLS 1
#define CONFIG_LIBUKDEBUG_ENABLE_ASSERT 1
#define CONFIG_LIBUKDEBUG_PRINT_TIME 1
#define CONFIG_LIBUKBOOT_BANNER 1
#define CONFIG_LIBUKBOOT_MAXNBARGS 60
#define CONFIG_LIBUKALLOC 1
#define CONFIG_PLAT_KVM 1
#define CONFIG_OPTIMIZE_DBGFILE 1
#define CONFIG_LIBFDT 1
#define CONFIG_LIBNOLIBC 1
#define CONFIG_UK_NAME "unikraft"
#define CONFIG_OPTIMIZE_STRIP 1
#define CONFIG_LIBUKBOOT 1
#define CONFIG_LIBUKBOOT_INITALLOC 1
#define CONFIG_ARCH_ARM_64 1
#define CONFIG_LIBUKALLOCBBUDDY 1
#define CONFIG_LIBUKARGPARSE 1
#define CONFIG_LIBUKDEBUG_REDIR_PRINTD 1
#define CONFIG_MARCH_ARM64_GENERIC 1
#define CONFIG_LIBUKDEBUG 1
#define CONFIG_LIBUKDEBUG_PRINTK_ERR 1
#define CONFIG_ARM64_ERRATUM_858921 1
#define CONFIG_LIBUKDEBUG_PRINTK 1
#define CONFIG_DEBUG_SYMBOLS_LVL3 1
#define CONFIG_HZ 100
#define CONFIG_HAVE_BOOTENTRY 1
#define CONFIG_OPTIMIZE_SYMFILE 1
#define CONFIG_OPTIMIZE_PERF 1
#define CONFIG_EARLY_PRINT_PL011_UART_ADDR 0x09000000
#define CONFIG_LIBUKALLOC_IFPAGES 1
#define CONFIG_LIBUKTIMECONV 1
#define CONFIG_KVM_DEBUG_SERIAL_CONSOLE 1
#define CONFIG_CROSS_COMPILE ""
